<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "factory_translate".
 *
 * @property integer $id
 * @property string $language
 * @property string $factoryname
 * @property integer $factoryid
 *
 * @property \backend\models\Factory $factory
 * @property string $aliasModel
 */
abstract class FactoryTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'factory_translate';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['factoryid'], 'integer'],
            [['language', 'factoryname'], 'string', 'max' => 45],
            [['factoryid'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Factory::className(), 'targetAttribute' => ['factoryid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'language' => Yii::t('models', 'Language'),
            'factoryname' => Yii::t('models', 'Factoryname'),
            'factoryid' => Yii::t('models', 'Factoryid'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFactory()
    {
        return $this->hasOne(\backend\models\Factory::className(), ['id' => 'factoryid']);
    }




}
