<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "factory".
 *
 * @property integer $id
 * @property string $logo
 * @property string $factoryname
 * @property integer $userid
 *
 * @property \backend\models\Customer[] $customers
 * @property \backend\models\FactoryTranslate[] $factoryTranslates
 * @property \backend\models\Position[] $positions
 * @property \backend\models\Stuff[] $stuffs
 * @property \backend\models\User $user
 * @property \backend\models\Water[] $waters
 * @property string $aliasModel
 */
abstract class Factory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'factory';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['factoryname', 'userid'], 'required'],
            [['userid'], 'integer'],
            [['logo'], 'string', 'max' => 255],
            [['factoryname'], 'string', 'max' => 200],
            [['userid'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['userid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'logo' => Yii::t('models', 'Logo'),
            'factoryname' => Yii::t('models', 'Factoryname'),
            'userid' => Yii::t('models', 'Userid'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomers()
    {
        return $this->hasMany(\backend\models\Customer::className(), ['factoryid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFactoryTranslates()
    {
        return $this->hasMany(\backend\models\FactoryTranslate::className(), ['factoryid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPositions()
    {
        return $this->hasMany(\backend\models\Position::className(), ['factoryid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStuffs()
    {
        return $this->hasMany(\backend\models\Stuff::className(), ['factory_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'userid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWaters()
    {
        return $this->hasMany(\backend\models\Water::className(), ['factoryid' => 'id']);
    }




}
