<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "language_translate".
 *
 * @property integer $id
 * @property string $language
 * @property string $translation
 *
 * @property \backend\models\LanguageSource $id0
 * @property \backend\models\Language $language0
 * @property string $aliasModel
 */
abstract class LanguageTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'language_translate';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'language'], 'required'],
            [['id'], 'integer'],
            [['translation'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['id', 'language'], 'unique', 'targetAttribute' => ['id', 'language']],
            [['language'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Language::className(), 'targetAttribute' => ['language' => 'language_id']],
            [['id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\LanguageSource::className(), 'targetAttribute' => ['id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'language' => Yii::t('models', 'Language'),
            'translation' => Yii::t('models', 'Translation'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getId0()
    {
        return $this->hasOne(\backend\models\LanguageSource::className(), ['id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLanguage0()
    {
        return $this->hasOne(\backend\models\Language::className(), ['language_id' => 'language']);
    }




}
