<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "language_source".
 *
 * @property integer $id
 * @property string $category
 * @property string $message
 *
 * @property \backend\models\LanguageTranslate[] $languageTranslates
 * @property \backend\models\Language[] $languages
 * @property string $aliasModel
 */
abstract class LanguageSource extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'language_source';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['message'], 'string'],
            [['category'], 'string', 'max' => 32]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'category' => Yii::t('models', 'Category'),
            'message' => Yii::t('models', 'Message'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLanguageTranslates()
    {
        return $this->hasMany(\backend\models\LanguageTranslate::className(), ['id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLanguages()
    {
        return $this->hasMany(\backend\models\Language::className(), ['language_id' => 'language'])->viaTable('language_translate', ['id' => 'id']);
    }




}
