<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "position".
 *
 * @property integer $id
 * @property string $positionname
 * @property string $salary
 * @property integer $factoryid
 * @property integer $userid
 *
 * @property \backend\models\Factory $factory
 * @property \backend\models\PositionTranslate[] $positionTranslates
 * @property \backend\models\Stuff[] $stuffs
 * @property string $aliasModel
 */
abstract class Position extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'position';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['positionname', 'salary', 'factoryid', 'userid'], 'required'],
            [['salary'], 'number'],
            [['factoryid', 'userid'], 'integer'],
            [['positionname'], 'string', 'max' => 255],
            [['factoryid'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Factory::className(), 'targetAttribute' => ['factoryid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'positionname' => Yii::t('models', 'Positionname'),
            'salary' => Yii::t('models', 'Salary'),
            'factoryid' => Yii::t('models', 'Factoryid'),
            'userid' => Yii::t('models', 'Userid'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFactory()
    {
        return $this->hasOne(\backend\models\Factory::className(), ['id' => 'factoryid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPositionTranslates()
    {
        return $this->hasMany(\backend\models\PositionTranslate::className(), ['positionid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStuffs()
    {
        return $this->hasMany(\backend\models\Stuff::className(), ['position_id' => 'id']);
    }




}
