<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "prepareforsellview".
 *
 * @property integer $id
 * @property integer $waterid
 * @property integer $quality
 * @property string $sellprice
 * @property string $amount
 * @property string $discount
 * @property string $amountdiscount
 * @property integer $customerid
 * @property integer $factoryid
 * @property integer $userid
 * @property string $aliasModel
 */
abstract class Prepareforsellview extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'prepareforsellview';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'waterid', 'quality', 'customerid', 'factoryid', 'userid'], 'integer'],
            [['waterid', 'quality', 'sellprice', 'factoryid', 'userid'], 'required'],
            [['sellprice', 'amount', 'discount', 'amountdiscount'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'waterid' => Yii::t('models', 'Waterid'),
            'quality' => Yii::t('models', 'Quality'),
            'sellprice' => Yii::t('models', 'Sellprice'),
            'amount' => Yii::t('models', 'Amount'),
            'discount' => Yii::t('models', 'Discount'),
            'amountdiscount' => Yii::t('models', 'Amountdiscount'),
            'customerid' => Yii::t('models', 'Customerid'),
            'factoryid' => Yii::t('models', 'Factoryid'),
            'userid' => Yii::t('models', 'Userid'),
        ];
    }




}
