<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "salarypaid".
 *
 * @property integer $id
 * @property string $date
 * @property string $time
 * @property string $salaryamount
 * @property integer $stuffid
 * @property integer $factoryid
 *
 * @property \backend\models\Stuff $stuff
 * @property string $aliasModel
 */
abstract class Salarypaid extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'salarypaid';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'date', 'time', 'salaryamount', 'stuffid', 'factoryid'], 'required'],
            [['id', 'stuffid', 'factoryid'], 'integer'],
            [['date', 'time'], 'safe'],
            [['salaryamount'], 'string', 'max' => 255],
            [['id'], 'unique'],
            [['stuffid'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Stuff::className(), 'targetAttribute' => ['stuffid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'date' => Yii::t('models', 'Date'),
            'time' => Yii::t('models', 'Time'),
            'salaryamount' => Yii::t('models', 'Salaryamount'),
            'stuffid' => Yii::t('models', 'Stuffid'),
            'factoryid' => Yii::t('models', 'Factoryid'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStuff()
    {
        return $this->hasOne(\backend\models\Stuff::className(), ['id' => 'stuffid']);
    }




}
