<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "unit".
 *
 * @property integer $id
 * @property string $unitname
 * @property integer $factoryid
 * @property integer $userid
 *
 * @property \backend\models\Factory $factory
 * @property \backend\models\Water[] $waters
 * @property string $aliasModel
 */
abstract class Unit extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'unit';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['unitname', 'factoryid', 'userid'], 'required'],
            [['factoryid', 'userid'], 'integer'],
            [['unitname'], 'string', 'max' => 10],
            [['factoryid'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Factory::className(), 'targetAttribute' => ['factoryid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'unitname' => Yii::t('models', 'Unitname'),
            'factoryid' => Yii::t('models', 'Factoryid'),
            'userid' => Yii::t('models', 'Userid'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFactory()
    {
        return $this->hasOne(\backend\models\Factory::className(), ['id' => 'factoryid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWaters()
    {
        return $this->hasMany(\backend\models\Water::className(), ['unitid' => 'id']);
    }




}
