<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "village".
 *
 * @property integer $id
 * @property string $villagename
 * @property integer $district_id
 * @property integer $province_id
 *
 * @property \backend\models\District $district
 * @property \backend\models\Province $province
 * @property string $aliasModel
 */
abstract class Village extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'village';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['district_id', 'province_id'], 'integer'],
            [['villagename'], 'string', 'max' => 255],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\District::className(), 'targetAttribute' => ['district_id' => 'id']],
            [['province_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Province::className(), 'targetAttribute' => ['province_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'villagename' => Yii::t('models', 'Villagename'),
            'district_id' => Yii::t('models', 'District ID'),
            'province_id' => Yii::t('models', 'Province ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(\backend\models\District::className(), ['id' => 'district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvince()
    {
        return $this->hasOne(\backend\models\Province::className(), ['id' => 'province_id']);
    }




}
