<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "water_translate".
 *
 * @property integer $id
 * @property integer $language
 * @property string $watername
 * @property integer $waterid
 *
 * @property \backend\models\Water $water
 * @property string $aliasModel
 */
abstract class WaterTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'water_translate';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['language', 'waterid'], 'integer'],
            [['watername'], 'string', 'max' => 10],
            [['waterid'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Water::className(), 'targetAttribute' => ['waterid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'language' => Yii::t('models', 'Language'),
            'watername' => Yii::t('models', 'Watername'),
            'waterid' => Yii::t('models', 'Waterid'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWater()
    {
        return $this->hasOne(\backend\models\Water::className(), ['id' => 'waterid']);
    }




}
