<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "wateradd".
 *
 * @property integer $id
 * @property string $date
 * @property string $time
 * @property integer $waterid
 * @property integer $quantity
 * @property integer $unitid
 * @property integer $factoryid
 * @property integer $userid
 *
 * @property \backend\models\Water $water
 * @property string $aliasModel
 */
abstract class Wateradd extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wateradd';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date', 'time', 'waterid', 'quantity', 'unitid', 'factoryid', 'userid'], 'required'],
            [['date', 'time'], 'safe'],
            [['waterid', 'quantity', 'unitid', 'factoryid', 'userid'], 'integer'],
            [['waterid'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Water::className(), 'targetAttribute' => ['waterid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'date' => Yii::t('models', 'Date'),
            'time' => Yii::t('models', 'Time'),
            'waterid' => Yii::t('models', 'Waterid'),
            'quantity' => Yii::t('models', 'Quantity'),
            'unitid' => Yii::t('models', 'Unitid'),
            'factoryid' => Yii::t('models', 'Factoryid'),
            'userid' => Yii::t('models', 'Userid'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWater()
    {
        return $this->hasOne(\backend\models\Water::className(), ['id' => 'waterid']);
    }




}
