<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "watersale".
 *
 * @property integer $id
 * @property string $date
 * @property string $time
 * @property integer $waterid
 * @property integer $quantity
 * @property integer $sellprice
 * @property string $amount
 * @property integer $discount
 * @property string $amountdiscount
 * @property string $totalreceiveamount
 * @property integer $customerid
 * @property string $billno
 * @property integer $stuffasuserid
 * @property integer $factoryid
 * @property integer $userid
 *
 * @property \backend\models\Water $water
 * @property string $aliasModel
 */
abstract class Watersale extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'watersale';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date', 'time', 'waterid', 'quantity', 'sellprice', 'amount', 'totalreceiveamount', 'billno', 'factoryid'], 'required'],
            [['date', 'time'], 'safe'],
            [['waterid', 'quantity', 'sellprice', 'discount', 'customerid', 'stuffasuserid', 'factoryid', 'userid'], 'integer'],
            [['amount', 'amountdiscount', 'totalreceiveamount'], 'number'],
            [['billno'], 'string', 'max' => 50],
            [['waterid'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Water::className(), 'targetAttribute' => ['waterid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'date' => Yii::t('models', 'Date'),
            'time' => Yii::t('models', 'Time'),
            'waterid' => Yii::t('models', 'Waterid'),
            'quantity' => Yii::t('models', 'Quantity'),
            'sellprice' => Yii::t('models', 'Sellprice'),
            'amount' => Yii::t('models', 'Amount'),
            'discount' => Yii::t('models', 'Discount'),
            'amountdiscount' => Yii::t('models', 'Amountdiscount'),
            'totalreceiveamount' => Yii::t('models', 'Totalreceiveamount'),
            'customerid' => Yii::t('models', 'Customerid'),
            'billno' => Yii::t('models', 'Billno'),
            'stuffasuserid' => Yii::t('models', 'Stuffasuserid'),
            'factoryid' => Yii::t('models', 'Factoryid'),
            'userid' => Yii::t('models', 'Userid'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWater()
    {
        return $this->hasOne(\backend\models\Water::className(), ['id' => 'waterid']);
    }




}
